from selenium.webdriver.common.by import By

    
L_USERNAME = (By.ID, 'edtUsuarioAD') 
L_UNLOCK_TOKEN = (By.ID, 'btnUsuario')  
L_SEND_SMS = (By.ID, 'btnEnviaSMS')
L_TOKEN_ENTRY = (By.ID, 'edtToken') #token ago
L_PASSWORD = (By.ID, 'edtSenhaAD')  
L_ENTER_TOKEN = (By.ID, 'btnUsuario') # avançar token
L_ENTER_LOGIN = (By.ID, 'btnLoginUsuario')  
L_VENDA = (By.ID, 'VE')
L_VENDA_DE_PROPOSTAS = (By.CLASS_NAME, 'link_active')
L_SIM_E_VE = (By.ID, 'ctl00_Conteudo_ctl00_tvwMenut3')
L_CPF_CONTRATANTE_ENTRY = (By.ID, 'ctl00_Conteudo_txtCD_Inscricao_Nacional')
L_SIMULAR = (By.ID, 'ctl00_Conteudo_btnSimular')
L_COMISSIONADO_ENTRY = (By.ID, 'ctl00_Conteudo_edtCdComissionado')    
L_PARCERIA = (By.ID, 'ctl00_Conteudo_tbTipoVenda_ctl00_btnTipoVenda')
L_EM_ANDAMENTO = (By.ID, 'ctl00_Conteudo_tbsituacao_ctl00_btnSituacaoGrupo')
L_PRAZO_INI = (By.ID, 'ctl00_Conteudo_edtPrazoInicial')
L_PRAZO_FIN = (By.ID, 'ctl00_Conteudo_edtPrazoFinal')
L_CONTINUE = (By.XPATH, '//*[@id="ctl00_Conteudo_btnContinuar"]') 
L_VOLTAR = (By.ID, 'ctl00_Conteudo_btnVoltar')
L_PAGES = (By.ID, 'tableGrupos_info')
L_NEXT_PAGE = (By.ID, 'tableGrupos_next')
L_PAGE_ONE = (By.CLASS_NAME, 'paginate_button ')
L_RADIO = (By.CLASS_NAME, 'input-radio')
L_RADIO_PROMO = (By.CSS_SELECTOR, 'td[class*="input-radio sorting_1"] input')
#L_RADIO = (By.CSS_SELECTOR, 'td[class*=" sorting_1"]')

L_TABLE_ITEMS = (By.ID, 'tableBens')
L_GROUP = (By.ID, 'ctl00_Conteudo_lblGrupo')
L_VENC = (By.ID, 'ctl00_Conteudo_lblDtVencimento')
L_TABLEBENS_INFO_PAGES = (By.ID, 'tableBens_info')
L_ERROR_MSG = (By.ID, 'ctl00_Conteudo_wucModal_lblMensagem')
L_TABLEBENS_NEXT = (By.ID, 'tableBens_next')
L_SENHA_ATUAL = (By.ID, 'edtSenhaAtual')
L_NOVA_SENHA = (By.ID, 'edtNovaSenha')
L_CONFIRMAR_NOVA_SENHA = (By.ID, 'edtConfirma')
L_BTN_CONFIRMAR = (By.ID, 'btnConfirmar')
L_TAM_SIT_GROUP = (By.ID, "ctl00_Conteudo_situacaoGrupo")
L_EM_FORMACAO = (By.ID, "ctl00_Conteudo_tbsituacao_ctl01_btnSituacaoGrupo")
L_PRAZ_NUM = (By.CSS_SELECTOR, '#ctl00_Conteudo_divPrazos button')
L_72 = (By.ID, 'ctl00_Conteudo_tbPrazos_ctl00_btnPrazo') 
L_90 = (By.ID, 'ctl00_Conteudo_tbPrazos_ctl01_btnPrazo') 
L_TABLEBENS = (By.ID, 'tableBens')
L_NEXT_PAGE_FORM = (By.ID, 'tableBens_next')
L_AUTO = (By.ID, 'ctl00_Conteudo_tbProdutos_ctl01_btnProduto')
L_TABLE_BENS = (By.ID, 'tableBens_wrapper')
L_CARRINHO = (By.ID, 'ctl00_Conteudo_btnAdicionarCarrinho')
L_ALERT_OK = (By.ID, 'ctl00_Conteudo_wucModal_botao')
L_CONTEUDO_CARRINHO = (By.ID, 'ctl00_Conteudo_wucStepSimulador_img_carrinho')
L_TABLE_CARRINHO = (By.ID, 'tbCarrinho')
#L_ALERT_OK = (By.ID, 'ctl00_Conteudo_wucModal_botao')
L_ERRO = (By.ID, 'ctl00_Conteudo_wucModal_lblTitulo')#(By.XPATH, "//*[contains(text(), 'Erro')]")
L_MESSAGE_ALERT = (By.ID, 'ctl00_Conteudo_wucModal_lblMensagem')
L_GROUP_TEXT = (By.CLASS_NAME, "text-left")
L_IMOVEL = (By.ID, 'ctl00_Conteudo_tbProdutos_ctl00_btnProduto')
L_AUTO = (By.ID, 'ctl00_Conteudo_tbProdutos_ctl01_btnProduto')
L_CAMINHAO = (By.ID, 'ctl00_Conteudo_tbProdutos_ctl02_btnProduto')
L_MOTO = (By.ID, 'ctl00_Conteudo_tbProdutos_ctl03_btnProduto') 
L_SMS_AGO = (By.ID, 'rblAcao_0' )
L_EMAIL = (By.ID, 'EMAIL')
L_ENVIA_EMAIL = (By.ID, 'btnEnviaEmail')
L_CONTEMPLACAO = (By.ID, 'CP')
L_VENDA_DE_PROPOSTAS = (By.CLASS_NAME, 'link_active')
L_RESULTADOS = (By.ID, 'ctl00_Conteudo_ctl00_tvwMenut1') 
L_GRUPO_SEARCH = (By.ID, 'ctl00_Conteudo_edtCD_Grupo')
L_CONFIRM_GROUP = (By.ID,'ctl00_Conteudo_btnOK')
L_QTD_AGO = (By.ID, 'ctl00_Conteudo_lblQT_Assembleia_Realizada')
L_LAST_AGO = (By.ID, 'ctl00_Conteudo_lblDT_Assembleia_Ex')	
L_BACK = (By.ID, 'ctl00_Conteudo_hlkVoltar')
L_LANCE_LIVRE = (By.ID, 'ctl00_Conteudo_lblTotalLL')
L_LAST_AGO = (By.ID, 'ctl00_Conteudo_lblDT_Assembleia_Ex')	
L_PREV = (By.ID, 'ctl00_Conteudo_btnRetornaAssembleia')
L_TABLE = (By.CSS_SELECTOR, '#ctl00_Conteudo_grdContemplacoes_Confirmadas tbody tr')
L_BACEN_ERROR = (By.XPATH, "/html/body/table/tbody/tr[6]/td[2]/font")
L_PROX_ASS = (By.ID, 'ctl00_Conteudo_lblDtAssembleia')
L_ATENCAO = (By.XPATH, "//*[contains(text(), 'Atenção')]")
L_CLOSE_BUTTON = (By.CSS_SELECTOR, 'button[class="close"]')

L_PROMO_IMOVEL = (By.ID, 'ctl00_Conteudo_tbDescontos_ctl00_btnDesconto')
L_PROMO_AUTO = (By.CSS_SELECTOR, '#ctl00_Conteudo_divDescontos button')
L_PROMO_AUTO_FORM = (By.CSS_SELECTOR, '#ctl00_Conteudo_divPrazoItem button')
L_PARCEL_TX_ANTECI = (By.CSS_SELECTOR, 'div[id="tableBens_wrapper"] table tbody td a')
L_PARC_ADESAO = (By.CSS_SELECTOR, 'table[class="table-detalhes-plano"] tbody')
L_CLOSE_TX = (By.XPATH, '//*[@id="modalDetalhePlano"]/div/div/div[1]/button')
L_NEXT_OFF = (By.CSS_SELECTOR, 'a[class"paginate_button next disabled"]')
L_CONTENT_INDEXAD = (By.CSS_SELECTOR, 'span[id="ctl00_Conteudo_lblAvisoSegmentoBem"]')